# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: 
    - "apis/user-java/**"

env:
  WORKDIR: 'apis/user-java'
    
# Set defaults for GitHub Actions runner
defaults:
  run:
    working-directory: "apis/user-java"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      #run: mvn -B package --file apis/user-java/pom.xml
      run: mvn test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JUnit Tests            # Name of the check run which will be created
        path: "${{ env.WORKDIR }}/target/surefire-reports/TEST-*.xml"  # Path to test results
        reporter: java-junit         # Format of test results
    
    - name: Riase Bug
      uses: JasonEtco/create-an-issue@v2
      if: failure()  
      env:
        GITHUB_TOKEN: ${{ secrets.OPENHACK_TOKEN }}
